#!/usr/bin/env bash

# command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-commit.\n"; exit 2; }
# git lfs post-commit "$@"

set -e

printf "\e[33;1m%s\e[0m\n" 'Running the linter'
bundle exec rake lint_fix
printf "\e[33;1m%s\e[0m\n" 'Finished running linter'
